default: &default
  disk_space_limit: <%= ENV.fetch("BACKUP_DISK_SPACE_LIMIT") { 10 } %>
  directory: <%= ENV.fetch("BACKUP_DIRECTORY") { "tmp/backups" } %>
  prefix: <%= ENV.fetch("BACKUP_PREFIX") { "decidim-backup" } %>
  timestamp_file: <%= ENV.fetch("BACKUP_TIMESTAMP_FILE") { "timestamp-backup.log" } %>
  s3sync:
    enabled: <%= ENV.fetch("BACKUP_S3SYNC_ENABLE") { false } %>
    region: <%= ENV.fetch("BACKUP_S3SYNC_REGION") { "fr-par" } %>
    endpoint: <%= ENV.fetch("BACKUP_S3SYNC_ENDPOINT") { "https://s3.fr-par.scw.cloud" } %>
    bucket: <%= ENV.fetch("BACKUP_S3SYNC_BUCKET") { nil } %>
    access_key: <%= ENV.fetch("BACKUP_S3SYNC_ACCESS_KEY") { nil } %>
    secret_key: <%= ENV.fetch("BACKUP_S3SYNC_SECRET_KEY") { nil } %>
    subfolder: <%= ENV.fetch("BACKUP_S3SYNC_SUBFOLDER") { nil } %>
    timestamp_file: <%= ENV.fetch("BACKUP_S3SYNC_TIMESTAMP_FILE") { "timestamp-sync.log" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default